sky:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  aliyun:
    endpoint: https://oss-cn-hangzhou.aliyuncs.com
    access-key-id: LTAI5tDV8aHnshyMcr2tu1ja
    access-key-secret: VLCzgkX6wpPxR0qolgfmjSA0gS5DQg
    bucket-name: web-tlias-liangguang
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 1
